import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import { useState, useEffect } from "react";

import type { Project } from '@/pages/api/getProjects';

import ProjectComponent from "@/components/project";

export default function Home() {

  const [hideTechnologies, setHideTechnologies] = useState<boolean>(false);
  const [hideProjects, setHideProjects] = useState<boolean>(false);

  const [projects, setProjects] = useState<Project[]>([]);

  useEffect(() => {
    fetch('/api/getProjects')
      .then(r => r.json() as Promise<Project[]>)
      .then(r => setProjects(r))
  }, [])

  const languages = ['Python', 'Javascript', 'PHP'];
  const databases = ['MySQL', 'PostgreSQL', 'SQLite'];
  const frontend_frameworks = ['NextJS', 'React'];
  const other_web_development = ['Prisma', 'Express', 'Flask'];
  const cloud = ['RDS', 'S3', 'CloudFront'];

  return (
    <>
    <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-l from-[#3b414c] to-[#0f124a] text-white max-w-full">
        <section className="py-7 flex flex-col justify-center items-center">
          <h1 className="font-bold text-6xl">
            Ciao! 👋
          </h1>
          <h3 className="font-bold text-xl p-2">
            I&apos;m Ilaria Migone, a web and Python developer.
          </h3>
          <p className="container text-center p-2">
           Besides programming, my other main interest is music: I have been playing the piano for over 13 years.
            You can see me perform Chopin&apos;s <i>Ballade no.1 in G minor</i> <Link target="_blank" href="https://youtu.be/0mc2nZkwsRU" className="text-white">here</Link>.
          </p>
          <p>
            Fun fact: I can speak three languages fluently; those are 🇮🇹, 🇪🇸 and 🇺🇸
          </p>
        </section>
        <section className="py-7 flex flex-col justify-center items-center max-w-full">
          <h1 className="text-4xl m-7">
            Technologies I have worked with: <button className="text-sm bg-transparent border-0 text-white" onClick={_ => {setHideTechnologies(!hideTechnologies)}}>{hideTechnologies ? "show" : "hide"}</button>
          </h1>
          <article style={{ display: hideTechnologies ? "none" : "block" }}>
            {
              [
                [languages, "Programming languages"],
                [databases, "Database programs"],
                [frontend_frameworks, "Web development frameworks"],
                [cloud, "Cloud"],
                [other_web_development, "Others for web development"]
              ].map((arr: (string | string[])[], i:number) => {
                return <div key={i}>
                <h3 key={'tech_h3_'+i.toString()} className="text-center">
                  {arr[1]}:
                </h3>
                <div key={'teach_div_'+i.toString()} className="m-10 flex flex-row flex-wrap justify-center">
                  {
                    // useless check, for ts
                    typeof(arr[0]) != "string" && arr[0]?.map((element: string, i: number) => <div key={"tech_image_"+i.toString()} className="w-48 h-48 relative m-3">
                    <Image className="p-3 bg-gradient-to-br to-[#ffffff] from-[#c8c8d7] rounded-xl object-contain" src={`/${element}-logo.png`} alt={element + " logo"} height={192} width={192}/>
                  </div>)
                  }
                </div>
                </div>
              })
            }
          </article>
        </section>
        <section className="py-7 flex flex-col justify-center items-center max-w-full">
          <h1 className="text-4xl m-7">
            Projects <button className="text-sm bg-transparent border-0 text-white" onClick={_ => {setHideProjects(!hideProjects)}}>{hideProjects ? "show" : "hide"}</button>
          </h1>
          {
            !hideProjects && projects.map((p, i) => <ProjectComponent key={i} n={i} project={p}/>)
          }
        </section>
        <section className="py-7 flex flex-col justify-center items-center max-w-full">
          <h1 className="text-4xl m-7">
            Contact me
          </h1>
          <form onSubmit={(e) => e.preventDefault()} className="container max-w-2xl">
          <div className="mb-6">
            <label htmlFor="name" className="block mb-2 text-sm font-medium text-white">Name</label>
            <input type="name" id="name" className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="John Doe" required/>
          </div>
          <div className="mb-6">
            <label htmlFor="email" className="block mb-2 text-sm font-medium  text-white">Your email</label>
            <input type="email" id="email" className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="johndoe@example.com" required/>
          </div>
          <div className="mb-6">
            <label htmlFor="description" className="block mb-2 text-sm font-medium  text-white">Please describe your request</label>
            <textarea id="description" className="text-sm rounded-lg w-full p-2.5 h-40"/>
          </div>
          </form>
        </section>
      </main>
    </>
  );
}
